- name: Install Android SDK & NDK
        run: |
          sudo apt install -y unzip wget
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          mkdir -p $HOME/Android/cmdline-tools
          unzip cmdline-tools.zip -d $HOME/Android/cmdline-tools
          yes | $HOME/Android/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android "platform-tools" "platforms;android-33" "ndk;25.2.9519653"

      - name: Build APK
        env:
          BUILDOZER_DISABLE_SDK_LICENSE_PROMPT: 1
          ANDROID_HOME: $HOME/Android
          ANDROID_SDK_ROOT: $HOME/Android
          ANDROID_NDK_ROOT: $HOME/Android/ndk/25.2.9519653
        run: |
          buildozer -v android debug
